name: bugsee_example
description: Demonstrates how to use the Bugsee plugin.

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: 0.13.3
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  bugsee:
    path: ../

# The following section is specific to Flutter.
flutter:
  uses-material-design: true